/** プリフィックス */
export const acePrefix = {
  MODE: "ace/mode/",
  THEME: "ace/theme/",
};

/** エディタのデフォルト */
export const aceDefault = {
  MODE: acePrefix.MODE + "typescript",
  THEME: acePrefix.THEME + "dracula",
};

export const aceLangs = {
  C_CPP: "c_cpp",
  C_SHARP: "csharp",
  CSS: "css",
  DART: "dart",
  DOCKER: "dockerfile",
  ELIXIR: "elixir",
  ELM: "elm",
  GO: "golang",
  GROOVY: "groovy",
  HAML: "haml",
  HASKELL: "haskell",
  HTML: "html",
  ERB: "html_ruby",
  EEX: "html_elixir",
  JS: "javascript",
  JAVA: "java",
  JSON: "json",
  JULIA: "julia",
  KOTLIN: "kotlin",
  LUA: "lua",
  MAKE_FILE: "makefile",
  MARKDOWN: "markdown",
  MYSQL: "mysql",
  OBJ_C: "objectivec",
  PERL: "perl",
  PHP: "php",
  PYTHON: "python",
  SHELL: "powershell",
  R: "r",
  RUBY: "ruby",
  RUST: "rust",
  SASS: "sass",
  SCALA: "scala",
  SCSS: "scss",
  SH: "sh",
  SWIFT: "swift",
  PLAIN_TEXT: "text",
  TOML: "toml",
  TS: "typescript",
  XML: "xml",
  YAML: "yaml",
};